#!/bin/bash
#set -ex
COMPOSE_YAML='docker-compose.yaml'
COMPOSE_PROJECT='odo'
DOCKER_COMPOSE="docker-compose --compatibility -f ${COMPOSE_YAML} -p ${COMPOSE_PROJECT}"
COMPOSE_CMD="${1-''}"
COMPOSE_SVC="${2-''}"
PRODUCT_ID="${3}"

function help_doc_cmd
{
    cat <<EOF
$0 <COMMAND>:
    start     - Up container(s) to start service(s)
    stop      - Stop container(s) to stop service(s)
    down      - Down all services
    restart   - Restart container(s) to restart service(s)
    list      - List container(s)
    license   - Generate JIRA/Confluence/Plugin license
EOF
    exit 1
}

function help_doc_svc
{
    cat <<EOF
$0 ${COMPOSE_CMD} <SERVICE>:
    all       - All Services
    ldap      - OpenLDAP and PhpLDAPAdmin
    ssp       - Self Service Password
    mysql     - MySQL
    jira      - Jira Software
    conf      - Confluence
    sonar     - SonarQube Community Edition
    jenkins   - Jenkins
    gitlab    - GitLab Community Edition
    harbor    - Harbor [Not Support]
    rancher   - Rancher
    jms       - JumpServer
    portal    - DevOps Portal [Not Support]
EOF
    exit 1
}

function help_doc_license
{
    cat <<EOF
$0 ${COMPOSE_CMD} <PRODUCT> [PRODUCT_ID]:
    jira          - Generate JIRA software license
    jira_plugin   - Generate JIRA plugin license, PRODUCT_ID is REQUIRED
                    jira_plugin's PRODUCT_ID is plugin ID
                    find it from JIRA application detail page
    conf          - Generate Confluence server license, PRODUCT_ID is REQUIRED
                    conf's PRODUCT_ID is server ID
                    find it from Confluence installation page
    conf_plugin   - Generate Confluence plugin license, PRODUCT_ID is REQUIRED
                    conf_plugin's PRODUCT_ID is plugin ID
                    find it from Confluence application detail page
EOF
    exit 1
}

function check_env
{
    for _tool in "docker" "docker-compose"
    do
        output=$(${_tool} --version 2>&1) || {
            echo -e "\033[33;6m${_tool} is required in this machine \033[0m"
            echo "${output}"
            exit 1
        }
    done
}

function check_odo_cli
{
    echo "start stop down restart list license" | grep -qw "${COMPOSE_CMD}" || help_doc_cmd
    if [[ "${COMPOSE_CMD}" == "license" ]]; then
        echo "jira jira_plugin conf conf_plugin" | grep -qw "${COMPOSE_SVC}" || help_doc_license
        [[ "${COMPOSE_SVC}" != "jira" ]] && [[ -z "${PRODUCT_ID}" ]] && help_doc_license
    elif [[ "${COMPOSE_CMD}" == "list" ]]; then
        return 0
    elif [[ "${COMPOSE_CMD}" == "down" ]]; then
        return 0
    else
#        echo "all ldap ssp mysql jira conf sonar jenkins gitlab harbor rancher jms" | grep -qw "${COMPOSE_SVC}" || help_doc_svc
        echo "all ldap ssp mysql jira conf sonar jenkins gitlab rancher jms" | grep -qw "${COMPOSE_SVC}" || help_doc_svc
    fi
    return 0
}

function check_odo_svc
{
    if [[ "${COMPOSE_SVC}" == "all" ]]; then
        COMPOSE_SVC=""
    elif [[ "${COMPOSE_SVC}" == "ldap" ]]; then
        COMPOSE_SVC="odo-openldap odo-phpldapadmin"
    else
        [[ "${COMPOSE_CMD}" == "license" ]] || COMPOSE_SVC="odo-${COMPOSE_SVC}"
    fi
}

function create_db_for_odo
{
    while true
    do
        sleep 1
        docker exec -it odo-mysql bash -c "mysql -uroot -pQualitySphere -e 'show full processlist;'" && break
    done
    docker exec -it odo-mysql bash -c "mysql -uroot -pQualitySphere -e 'CREATE DATABASE IF NOT EXISTS jira DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_bin;'"
    docker exec -it odo-mysql bash -c "mysql -uroot -pQualitySphere -e 'CREATE DATABASE IF NOT EXISTS conf DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_bin;'"
    docker exec -it odo-mysql bash -c "mysql -uroot -pQualitySphere -e 'CREATE DATABASE IF NOT EXISTS sonar DEFAULT CHARSET utf8 COLLATE utf8_bin;'"
}

function chmod_dir
{
    dir_name=$1
    while true
    do
        sleep 1
        [[ -d ${dir_name} ]] && break
    done
    chmod -R 777 odo-jenkins
}

function set_host_for_sonar
{
    [[ "$(uname)" == "Linux" ]] && {
        sysctl -w vm.max_map_count=262144
        sysctl -w fs.file-max=65536
        ulimit -n 65536
        ulimit -u 4096
    }
}

## Main
check_env
check_odo_cli
check_odo_svc
if [[ "${COMPOSE_CMD}" == "start" ]]; then
    if [[ "${COMPOSE_SVC}" == "" ]]; then
        set_host_for_sonar
    else
        echo "${COMPOSE_SVC}" | grep "sonar" && set_host_for_sonar
    fi
    ${DOCKER_COMPOSE} pull ${COMPOSE_SVC}
    ${DOCKER_COMPOSE} up -d ${COMPOSE_SVC}
    if [[ "${COMPOSE_SVC}" == "" ]]; then
        chmod_dir odo-jenkins
        create_db_for_odo
    else
        echo "${COMPOSE_SVC}" | grep "mysql" && create_db_for_odo
        echo "${COMPOSE_SVC}" | grep "jenkins" && chmod_dir odo-jenkins
    fi
    sleep 2
    ${DOCKER_COMPOSE} ps
elif [[ "${COMPOSE_CMD}" == "stop" ]]; then
    ${DOCKER_COMPOSE} stop ${COMPOSE_SVC}
    sleep 2
    ${DOCKER_COMPOSE} ps
elif [[ "${COMPOSE_CMD}" == "restart" ]]; then
    ${DOCKER_COMPOSE} restart ${COMPOSE_SVC}
    sleep 2
    ${DOCKER_COMPOSE} ps
elif [[ "${COMPOSE_CMD}" == "list" ]]; then
    ${DOCKER_COMPOSE} ps
elif [[ "${COMPOSE_CMD}" == "down" ]]; then
    ${DOCKER_COMPOSE} down
    sleep 2
    ${DOCKER_COMPOSE} ps
elif [[ "${COMPOSE_CMD}" == "license" ]]; then
    if [[ "${COMPOSE_SVC}" == "jira" ]]; then
        docker exec -it odo-jira getJiraLicense
    elif [[ "${COMPOSE_SVC}" == "jira_plugin" ]]; then
        docker exec -it odo-jira getPluginLicense ${PRODUCT_ID}
    elif [[ "${COMPOSE_SVC}" == "conf" ]]; then
        docker exec -it odo-jira getConfLicense ${PRODUCT_ID}
    elif [[ "${COMPOSE_SVC}" == "conf_plugin" ]]; then
        docker exec -it odo-jira getPluginLicense ${PRODUCT_ID}
    fi
fi
